import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter_file_dialog/flutter_file_dialog.dart';
// import 'package:document_file_save_plus/document_file_save_plus.dart'; // Remove or comment out this line
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

class PdfScreen extends StatefulWidget {
  const PdfScreen({super.key});

  @override
  State<PdfScreen> createState() => _PdfScreenState();
}

class _PdfScreenState extends State<PdfScreen> {
  Uint8List? _pdfBytes;
  String? _pdfName;
  bool _isPdfGenerated = false;
  bool _isLoading = false;
  String _statusMessage = '';

  Future<void> _pickPdfFile() async {
    try {
      setState(() {
        _isLoading = true;
        _statusMessage = 'Selecting PDF file...';
      });

      // Pick a PDF file using flutter_file_dialog
      final params = OpenFileDialogParams(
        dialogType: OpenFileDialogType.document,
        sourceType: SourceType.photoLibrary,
        fileExtensionsFilter: ['pdf'],
      );
      
      final filePath = await FlutterFileDialog.pickFile(params: params);

      if (filePath != null) {
        final file = File(filePath);
        final bytes = await file.readAsBytes();
        final fileName = filePath.split('/').last;
        
        setState(() {
          _pdfBytes = bytes;
          _pdfName = fileName;
          _statusMessage = 'PDF selected: $fileName';
          _isPdfGenerated = false;
        });
      } else {
        setState(() {
          _statusMessage = 'No file selected';
        });
      }
    } catch (e) {
      setState(() {
        _statusMessage = 'Error selecting PDF: $e';
      });
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  Future<void> _generatePdf() async {
    try {
      setState(() {
        _isLoading = true;
        _statusMessage = 'Generating PDF...';
      });

      // Create a PDF document
      final pdf = pw.Document();

      // Add a page to the PDF
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Header(
                  level: 0,
                  child: pw.Text('PHR App Sample Report'),
                ),
                pw.SizedBox(height: 20),
                pw.Text('Generated at: ${DateTime.now().toString()}'),
                pw.SizedBox(height: 20),
                pw.Paragraph(
                  text: 'This is a sample report generated by the PHR App. '
                      'In a real app, this would contain actual patient health data.',
                ),
                pw.SizedBox(height: 20),
                pw.Table.fromTextArray(
                  headers: ['Date', 'Measurement', 'Value', 'Unit'],
                  data: [
                    ['${DateTime.now().toString().split(' ')[0]}', 'Blood Pressure', '120/80', 'mmHg'],
                    ['${DateTime.now().toString().split(' ')[0]}', 'Heart Rate', '72', 'bpm'],
                    ['${DateTime.now().toString().split(' ')[0]}', 'Temperature', '36.6', '°C'],
                    ['${DateTime.now().toString().split(' ')[0]}', 'Weight', '70', 'kg'],
                  ],
                ),
                pw.SizedBox(height: 40),
                pw.Paragraph(
                  text: 'This document is for testing purposes only and does not contain real medical information.',
                  style: pw.TextStyle(
                    font: pw.Font.helveticaOblique(),
                    fontSize: 10,
                    color: PdfColors.grey,
                  ),
                ),
              ],
            );
          },
        ),
      );

      // Get the PDF as bytes
      final bytes = await pdf.save();
      
      setState(() {
        _pdfBytes = bytes;
        _pdfName = 'sample_report.pdf';
        _isPdfGenerated = true;
        _statusMessage = 'PDF generated successfully';
      });
    } catch (e) {
      setState(() {
        _statusMessage = 'Error generating PDF: $e';
      });
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  Future<void> _printPdf() async {
    if (_pdfBytes == null) {
      setState(() {
        _statusMessage = 'No PDF file to print';
      });
      return;
    }

    try {
      setState(() {
        _isLoading = true;
        _statusMessage = 'Preparing to print...';
      });

      await Printing.layoutPdf(
        onLayout: (_) => _pdfBytes!,
      );

      setState(() {
        _statusMessage = 'Print dialog displayed';
      });
    } catch (e) {
      setState(() {
        _statusMessage = 'Error printing PDF: $e';
      });
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  Future<void> _sharePdf() async {
    if (_pdfBytes == null) {
      setState(() {
        _statusMessage = 'No PDF file to share';
      });
      return;
    }

    try {
      setState(() {
        _isLoading = true;
        _statusMessage = 'Preparing PDF for sharing...';
      });

      // Save the PDF to a temporary file
      final tempDir = await getTemporaryDirectory();
      final filePath = '${tempDir.path}/${_pdfName ?? 'shared_document.pdf'}';
      final file = File(filePath);
      await file.writeAsBytes(_pdfBytes!);

      // Share the file using share_plus
      final xFile = XFile(filePath);
      await Share.shareXFiles([xFile], text: 'Check out this PDF: ${_pdfName ?? ''}');
      
      setState(() {
        _statusMessage = 'Share dialog opened';
      });
    } catch (e) {
      setState(() {
        _statusMessage = 'Error sharing PDF: $e';
      });
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('PDF Handling'),
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Status display
            if (_statusMessage.isNotEmpty)
              Container(
                padding: const EdgeInsets.all(12),
                margin: const EdgeInsets.only(bottom: 16),
                decoration: BoxDecoration(
                  color: _statusMessage.contains('Error')
                      ? Colors.red.shade100
                      : Colors.blue.shade100,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Row(
                  children: [
                    Icon(
                      _statusMessage.contains('Error')
                          ? Icons.error_outline
                          : Icons.info_outline,
                      color: _statusMessage.contains('Error')
                          ? Colors.red
                          : Colors.blue,
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        _statusMessage,
                        style: TextStyle(
                          color: _statusMessage.contains('Error')
                              ? Colors.red
                              : Colors.blue,
                        ),
                      ),
                    ),
                  ],
                ),
              ),

            // Loading indicator
            if (_isLoading)
              const LinearProgressIndicator(
                backgroundColor: Colors.grey,
                valueColor: AlwaysStoppedAnimation<Color>(Colors.blue),
              ),

            // PDF Preview area
            Expanded(
              child: Container(
                margin: const EdgeInsets.symmetric(vertical: 16),
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.grey.shade300),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: _pdfBytes != null
                    ? PdfPreview(
                        maxPageWidth: 700,
                        build: (format) => _pdfBytes!,
                        canChangePageFormat: false,
                        canChangeOrientation: false,
                        canDebug: false,
                      )
                    : const Center(
                        child: Text(
                          'No PDF selected or generated',
                          style: TextStyle(color: Colors.grey),
                        ),
                      ),
              ),
            ),

            // Action buttons
            Card(
              elevation: 4,
              child: Padding(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    const Text(
                      'PDF Actions',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Expanded(
                          child: ElevatedButton.icon(
                            onPressed: _pickPdfFile,
                            icon: const Icon(Icons.file_upload),
                            label: const Text('Upload PDF'),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: Colors.blue,
                              foregroundColor: Colors.white,
                            ),
                          ),
                        ),
                        const SizedBox(width: 8),
                        Expanded(
                          child: ElevatedButton.icon(
                            onPressed: _generatePdf,
                            icon: const Icon(Icons.create),
                            label: const Text('Generate PDF'),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: Colors.green,
                              foregroundColor: Colors.white,
                            ),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Row(
                      children: [
                        Expanded(
                          child: OutlinedButton.icon(
                            onPressed:
                                _pdfBytes != null ? _printPdf : null,
                            icon: const Icon(Icons.print),
                            label: const Text('Print PDF'),
                          ),
                        ),
                        const SizedBox(width: 8),
                        Expanded(
                          child: OutlinedButton.icon(
                            onPressed:
                                _pdfBytes != null ? _sharePdf : null,
                            icon: const Icon(Icons.share),
                            label: const Text('Share PDF'),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
} 